<?php

namespace Reedware\Weather\Tests\Feature;

use Carbon\Carbon;
use Illuminate\Filesystem\FilesystemServiceProvider;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;
use Reedware\Weather\Drivers\WeatherApi\DTO\AirQuality;
use Reedware\Weather\Drivers\WeatherApi\DTO\Alert;
use Reedware\Weather\Drivers\WeatherApi\DTO\Astro;
use Reedware\Weather\Drivers\WeatherApi\DTO\Condition;
use Reedware\Weather\Drivers\WeatherApi\DTO\Current;
use Reedware\Weather\Drivers\WeatherApi\DTO\Day;
use Reedware\Weather\Drivers\WeatherApi\DTO\Enums\MoonPhase;
use Reedware\Weather\Drivers\WeatherApi\DTO\Enums\UkDefraIndex;
use Reedware\Weather\Drivers\WeatherApi\DTO\Enums\UsEpaIndex;
use Reedware\Weather\Drivers\WeatherApi\DTO\ForecastDay;
use Reedware\Weather\Drivers\WeatherApi\DTO\Hour;
use Reedware\Weather\Drivers\WeatherApi\DTO\Location;
use Reedware\Weather\Tests\TestCase as UnitTestCase;

class TestCase extends UnitTestCase
{
    /**
     * Sets up the environment before each test.
     */
    protected function setUp(): void
    {
        parent::setUp();

        $this->registerServiceProvider(FilesystemServiceProvider::class);
    
        Carbon::setTestNow('2023-06-01');
        Http::preventStrayRequests();
    
        $this->mockConfig([
            'weather' => [
                'default' => 'weather-api',
                'connections' => [
                    'weather-api' => [
                        'driver' => 'weatherApi',
                        'key' => ':secret:'
                    ]
                ]
            ]
        ]);
    }

    /**
     * Fakes the specified response.
     */
    protected function fakeResponse(string $uri, array $parameters, string $file, int $status = 200)
    {
        $url = sprintf(
            'https://api.weatherapi.com/v1/%s.json?%s',
            $uri,
            http_build_query(array_merge($parameters, [
                'key' => ':secret:'
            ]))
        );

        $contents = File::get(implode(DIRECTORY_SEPARATOR, [
            __DIR__,        // ~/tests/src/Feature
            '..',           // ~/tests/src
            '..',           // ~/tests
            'responses',    // ~/tests/responses
            $file . '.json' // ~/tests/responses/<file>.json
        ]));

        $response = Http::response($contents, $status);

        Http::fake([
            $url => $response
        ]);
    }

    /**
     * Creates a new location dto.
     */
    protected function newLocation(): Location
    {
        return new Location(
            id: null,
            name: 'Little Elm',
            region: 'Texas',
            country: 'USA',
            lat: 33.22,
            lon: -96.91,
            tz_id: 'America/Chicago',
            localtime_epoch: 1685637910,
            localtime: Carbon::parse('2023-06-01 11:45', 'UTC'),
            url: null
        );
    }

    /**
     * Creates a new current dto.
     */
    protected function newCurrent(bool $aqi = false): Current
    {
        return new Current(
            last_updated_epoch: 1685637000,
            last_updated: Carbon::parse('2023-06-01 11:30', 'UTC'),
            temp_c: 28.0,
            temp_f: 82.4,
            is_day: true,
            condition: new Condition(
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003
            ),
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 200,
            wind_dir: 'SSW',
            pressure_mb: 1015.0,
            pressure_in: 29.96,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 58,
            cloud: 50,
            feelslike_c: 30.0,
            feelslike_f: 85.9,
            vis_km: 16.0,
            vis_miles: 9.0,
            uv: 7.0,
            gust_mph: 9.2,
            gust_kph: 14.8,
            air_quality: ! $aqi ? null : new AirQuality(
                co: 320.3999938964844,
                no2: 11.100000381469727,
                o3: 125.9000015258789,
                so2: 4.199999809265137,
                pm2_5: 12.0,
                pm10: 14.0,
                us_epa_index: UsEpaIndex::GOOD,
                gb_defra_index: UkDefraIndex::TWO
            )
        );
    }

    /**
     * Creates a new forecast day dto.
     */
    protected function newForecastDay(string $dt, bool $aqi = false, bool $expanded = true): ForecastDay
    {
        return new ForecastDay(
            date: Carbon::parse($dt, 'UTC'),
            date_epoch: Carbon::parse($dt, 'UTC')->timestamp,
            day: new Day(
                maxtemp_c: 31.0,
                maxtemp_f: 87.8,
                mintemp_c: 21.0,
                mintemp_f: 69.8,
                avgtemp_c: 25.6,
                avgtemp_f: 78.1,
                maxwind_mph: 12.5,
                maxwind_kph: 20.2,
                totalprecip_mm: 0.4,
                totalprecip_in: 0.02,
                totalsnow_cm: $expanded ? 0.0 : null,
                avgvis_km: 10.0,
                avgvis_miles: 6.0,
                avghumidity: 68.0,
                daily_will_it_rain: $expanded ? 1 : null,
                daily_chance_of_rain: $expanded ? 84 : null,
                daily_will_it_snow: $expanded ? 0 : null,
                daily_chance_of_snow: $expanded ? 0 : null,
                condition: new Condition(
                    text: 'Patchy rain possible',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                    code: 1063
                ),
                uv: 6.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 331.1239978027344,
                    no2: 13.716000108718871,
                    o3: 78.48800025939941,
                    so2: 2.0200000047683715,
                    pm2_5: 12.403999938964844,
                    pm10: 14.012000160217285,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::TWO
                )
            ),
            astro: new Astro(
                sunrise: '06:19 AM',
                sunset: '08:31 PM',
                moonrise: '06:13 PM',
                moonset: '04:24 AM',
                moon_phase: MoonPhase::WAXING_GIBBOUS,
                moon_illumination: 88,
                is_moon_up: $expanded ? true : null,
                is_sun_up: $expanded ? true : null
            ),
            tides: null,
            hours: $this->newHours($dt, $aqi)
        );
    }

    /**
     * Creates a new forecast day dto.
     */
    protected function newFutureForecastDay(string $dt): ForecastDay
    {
        return new ForecastDay(
            date: Carbon::parse($dt, 'UTC'),
            date_epoch: Carbon::parse($dt, 'UTC')->timestamp,
            day: new Day(
                maxtemp_c: 31.0,
                maxtemp_f: 87.8,
                mintemp_c: 21.0,
                mintemp_f: 69.8,
                avgtemp_c: 25.6,
                avgtemp_f: 78.1,
                maxwind_mph: 12.5,
                maxwind_kph: 20.2,
                totalprecip_mm: 0.4,
                totalprecip_in: 0.02,
                totalsnow_cm: 0.0,
                avgvis_km: 10.0,
                avgvis_miles: 6.0,
                avghumidity: 68.0,
                daily_will_it_rain: null,
                daily_chance_of_rain: null,
                daily_will_it_snow: null,
                daily_chance_of_snow: null,
                condition: new Condition(
                    text: '',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/356.png',
                    code: 1243
                ),
                uv: 6.0,
                air_quality: null
            ),
            astro: new Astro(
                sunrise: '06:19 AM',
                sunset: '08:31 PM',
                moonrise: '06:13 PM',
                moonset: '04:24 AM',
                moon_phase: MoonPhase::WAXING_GIBBOUS,
                moon_illumination: 88,
                is_moon_up: null,
                is_sun_up: null
            ),
            tides: null,
            hours: $this->newFutureHours('2023-07-01')
        );
    }

    /**
     * Creates the hours for a forecast day.
     */
    protected function newHours(string $dt, bool $aqi = false): array
    {
        return [
            new Hour(
                time_epoch: Carbon::parse($dt . ' 00:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 00:00', 'UTC'),
                temp_c: 23.4,
                temp_f: 74.1,
                is_day: false,
                condition: new Condition(
                    text: 'Patchy rain possible',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                    code: 1063
                ),
                wind_mph: 8.1,
                wind_kph: 13.0,
                wind_degree: 138,
                wind_dir: 'SE',
                pressure_mb: 1011.0,
                pressure_in: 29.86,
                precip_mm: 0.1,
                precip_in: 0.0,
                humidity: 77,
                cloud: 80,
                feelslike_c: 25.3,
                feelslike_f: 77.5,
                windchill_c: 23.4,
                windchill_f: 74.1,
                heatindex_c: 25.3,
                heatindex_f: 77.5,
                dewpoint_c: 19.1,
                dewpoint_f: 66.4,
                will_it_rain: 0,
                chance_of_rain: 61,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 16.6,
                gust_kph: 26.6,
                uv: 1.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 380.5,
                    no2: 26.100000381469727,
                    o3: 39.70000076293945,
                    so2: 2.5999999046325684,
                    pm2_5: 13.0,
                    pm10: 14.800000190734863,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::TWO
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 01:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 01:00', 'UTC'),
                temp_c: 22.9,
                temp_f: 73.2,
                is_day: 0,
                condition: new Condition(
                    text: 'Patchy rain possible',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                    code: 1063
                ),
                wind_mph: 7.8,
                wind_kph: 12.6,
                wind_degree: 143,
                wind_dir: 'SE',
                pressure_mb: 1011.0,
                pressure_in: 29.86,
                precip_mm: 0.1,
                precip_in: 0.0,
                humidity: 80,
                cloud: 85,
                feelslike_c: 25.0,
                feelslike_f: 77.0,
                windchill_c: 22.9,
                windchill_f: 73.2,
                heatindex_c: 25.0,
                heatindex_f: 77.0,
                dewpoint_c: 19.2,
                dewpoint_f: 66.6,
                will_it_rain: 1,
                chance_of_rain: 84,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 15.7,
                gust_kph: 25.2,
                uv: 1.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 380.5,
                    no2: 26.100000381469727,
                    o3: 34.70000076293945,
                    so2: 2.200000047683716,
                    pm2_5: 13.5,
                    pm10: 15.399999618530273,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::TWO
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 02:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 02:00', 'UTC'),
                temp_c: 22.4,
                temp_f: 72.3,
                is_day: 0,
                condition: new Condition(
                    text: 'Clear',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                    code: 1000
                ),
                wind_mph: 7.2,
                wind_kph: 11.5,
                wind_degree: 142,
                wind_dir: 'SE',
                pressure_mb: 1011.0,
                pressure_in: 29.85,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 82,
                cloud: 5,
                feelslike_c: 24.7,
                feelslike_f: 76.5,
                windchill_c: 22.4,
                windchill_f: 72.3,
                heatindex_c: 24.7,
                heatindex_f: 76.5,
                dewpoint_c: 19.1,
                dewpoint_f: 66.4,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 14.1,
                gust_kph: 22.7,
                uv: 1.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 370.5,
                    no2: 23.700000762939453,
                    o3: 30.799999237060547,
                    so2: 1.7000000476837158,
                    pm2_5: 13.899999618530273,
                    pm10: 15.800000190734863,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::TWO
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 03:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 03:00', 'UTC'),
                temp_c: 22.0,
                temp_f: 71.6,
                is_day: 0,
                condition: new Condition(
                    text: 'Clear',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                    code: 1000
                ),
                wind_mph: 6.0,
                wind_kph: 9.7,
                wind_degree: 148,
                wind_dir: 'SSE',
                pressure_mb: 1011.0,
                pressure_in: 29.86,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 83,
                cloud: 6,
                feelslike_c: 24.5,
                feelslike_f: 76.1,
                windchill_c: 22.0,
                windchill_f: 71.6,
                heatindex_c: 24.5,
                heatindex_f: 76.1,
                dewpoint_c: 19.1,
                dewpoint_f: 66.4,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 11.9,
                gust_kph: 19.1,
                uv: 1.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 353.79998779296875,
                    no2: 20.200000762939453,
                    o3: 26.799999237060547,
                    so2: 1.100000023841858,
                    pm2_5: 14.100000381469727,
                    pm10: 16.0,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::TWO
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 04:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 04:00', 'UTC'),
                temp_c: 21.7,
                temp_f: 71.1,
                is_day: 0,
                condition: new Condition(
                    text: 'Patchy rain possible',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                    code: 1063
                ),
                wind_mph: 5.6,
                wind_kph: 9.0,
                wind_degree: 132,
                wind_dir: 'SE',
                pressure_mb: 1011.0,
                pressure_in: 29.87,
                precip_mm: 0.1,
                precip_in: 0.0,
                humidity: 85,
                cloud: 79,
                feelslike_c: 21.7,
                feelslike_f: 71.1,
                windchill_c: 21.7,
                windchill_f: 71.1,
                heatindex_c: 24.4,
                heatindex_f: 75.9,
                dewpoint_c: 19.0,
                dewpoint_f: 66.2,
                will_it_rain: 0,
                chance_of_rain: 63,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 11.0,
                gust_kph: 17.6,
                uv: 1.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 340.5,
                    no2: 17.299999237060547,
                    o3: 23.299999237060547,
                    so2: 0.8999999761581421,
                    pm2_5: 14.199999809265137,
                    pm10: 16.100000381469727,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::TWO
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 05:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 05:00', 'UTC'),
                temp_c: 21.4,
                temp_f: 70.5,
                is_day: 0,
                condition: new Condition(
                    text: 'Clear',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                    code: 1000
                ),
                wind_mph: 6.7,
                wind_kph: 10.8,
                wind_degree: 144,
                wind_dir: 'SE',
                pressure_mb: 1011.0,
                pressure_in: 29.86,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 86,
                cloud: 5,
                feelslike_c: 21.4,
                feelslike_f: 70.5,
                windchill_c: 21.4,
                windchill_f: 70.5,
                heatindex_c: 24.3,
                heatindex_f: 75.7,
                dewpoint_c: 19.0,
                dewpoint_f: 66.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 13.0,
                gust_kph: 20.9,
                uv: 1.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 323.79998779296875,
                    no2: 15.300000190734863,
                    o3: 20.200000762939453,
                    so2: 0.699999988079071,
                    pm2_5: 14.199999809265137,
                    pm10: 16.100000381469727,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::TWO
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 06:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 06:00', 'UTC'),
                temp_c: 21.0,
                temp_f: 69.8,
                is_day: 0,
                condition: new Condition(
                    text: 'Clear',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                    code: 1000
                ),
                wind_mph: 7.4,
                wind_kph: 11.9,
                wind_degree: 152,
                wind_dir: 'SSE',
                pressure_mb: 1012.0,
                pressure_in: 29.87,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 88,
                cloud: 5,
                feelslike_c: 21.0,
                feelslike_f: 69.8,
                windchill_c: 21.0,
                windchill_f: 69.8,
                heatindex_c: 21.0,
                heatindex_f: 69.8,
                dewpoint_c: 19.0,
                dewpoint_f: 66.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 13.4,
                gust_kph: 21.6,
                uv: 1.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 317.1000061035156,
                    no2: 14.600000381469727,
                    o3: 16.799999237060547,
                    so2: 0.6000000238418579,
                    pm2_5: 14.100000381469727,
                    pm10: 16.100000381469727,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::TWO
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 07:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 07:00', 'UTC'),
                temp_c: 21.2,
                temp_f: 70.2,
                is_day: 1,
                condition: new Condition(
                    text: 'Patchy rain possible',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                    code: 1063
                ),
                wind_mph: 6.5,
                wind_kph: 10.4,
                wind_degree: 147,
                wind_dir: 'SSE',
                pressure_mb: 1012.0,
                pressure_in: 29.88,
                precip_mm: 0.1,
                precip_in: 0.0,
                humidity: 89,
                cloud: 84,
                feelslike_c: 21.2,
                feelslike_f: 70.2,
                windchill_c: 21.2,
                windchill_f: 70.2,
                heatindex_c: 24.2,
                heatindex_f: 75.6,
                dewpoint_c: 19.2,
                dewpoint_f: 66.6,
                will_it_rain: 1,
                chance_of_rain: 81,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 11.2,
                gust_kph: 18.0,
                uv: 5.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 327.1000061035156,
                    no2: 17.299999237060547,
                    o3: 10.600000381469727,
                    so2: 0.6000000238418579,
                    pm2_5: 14.399999618530273,
                    pm10: 16.399999618530273,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::TWO
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 08:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 08:00', 'UTC'),
                temp_c: 22.8,
                temp_f: 73.0,
                is_day: 1,
                condition: new Condition(
                    text: 'Sunny',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                    code: 1000
                ),
                wind_mph: 6.9,
                wind_kph: 11.2,
                wind_degree: 162,
                wind_dir: 'SSE',
                pressure_mb: 1013.0,
                pressure_in: 29.91,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 82,
                cloud: 11,
                feelslike_c: 24.9,
                feelslike_f: 76.8,
                windchill_c: 22.8,
                windchill_f: 73.0,
                heatindex_c: 24.9,
                heatindex_f: 76.8,
                dewpoint_c: 19.5,
                dewpoint_f: 67.1,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 9.6,
                gust_kph: 15.5,
                uv: 6.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 373.79998779296875,
                    no2: 19.0,
                    o3: 8.899999618530273,
                    so2: 0.6000000238418579,
                    pm2_5: 15.0,
                    pm10: 17.200000762939453,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::TWO
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 09:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 09:00', 'UTC'),
                temp_c: 24.4,
                temp_f: 75.9,
                is_day: 1,
                condition: new Condition(
                    text: 'Sunny',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                    code: 1000
                ),
                wind_mph: 8.1,
                wind_kph: 13.0,
                wind_degree: 165,
                wind_dir: 'SSE',
                pressure_mb: 1013.0,
                pressure_in: 29.92,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 74,
                cloud: 10,
                feelslike_c: 26.2,
                feelslike_f: 79.2,
                windchill_c: 24.4,
                windchill_f: 75.9,
                heatindex_c: 26.2,
                heatindex_f: 79.2,
                dewpoint_c: 19.6,
                dewpoint_f: 67.3,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 9.6,
                gust_kph: 15.5,
                uv: 6.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 447.29998779296875,
                    no2: 21.600000381469727,
                    o3: 14.5,
                    so2: 0.800000011920929,
                    pm2_5: 16.200000762939453,
                    pm10: 18.600000381469727,
                    us_epa_index: UsEpaIndex::MODERATE,
                    gb_defra_index: UkDefraIndex::TWO
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 10:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 10:00', 'UTC'),
                temp_c: 25.9,
                temp_f: 78.6,
                is_day: 1,
                condition: new Condition(
                    text: 'Sunny',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                    code: 1000
                ),
                wind_mph: 8.5,
                wind_kph: 13.7,
                wind_degree: 157,
                wind_dir: 'SSE',
                pressure_mb: 1013.0,
                pressure_in: 29.91,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 68,
                cloud: 12,
                feelslike_c: 27.6,
                feelslike_f: 81.7,
                windchill_c: 25.9,
                windchill_f: 78.6,
                heatindex_c: 27.6,
                heatindex_f: 81.7,
                dewpoint_c: 19.6,
                dewpoint_f: 67.3,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 9.8,
                gust_kph: 15.8,
                uv: 7.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 534.0999755859375,
                    no2: 32.900001525878906,
                    o3: 27.899999618530273,
                    so2: 1.2999999523162842,
                    pm2_5: 17.899999618530273,
                    pm10: 20.700000762939453,
                    us_epa_index: UsEpaIndex::MODERATE,
                    gb_defra_index: UkDefraIndex::TWO
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 11:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 11:00', 'UTC'),
                temp_c: 28.3,
                temp_f: 82.9,
                is_day: 1,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                    code: 1003
                ),
                wind_mph: 8.1,
                wind_kph: 13.0,
                wind_degree: 176,
                wind_dir: 'S',
                pressure_mb: 1013.0,
                pressure_in: 29.92,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 62,
                cloud: 31,
                feelslike_c: 30.4,
                feelslike_f: 86.7,
                windchill_c: 28.3,
                windchill_f: 82.9,
                heatindex_c: 30.4,
                heatindex_f: 86.7,
                dewpoint_c: 20.4,
                dewpoint_f: 68.7,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 9.2,
                gust_kph: 14.8,
                uv: 7.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 320.3999938964844,
                    no2: 11.100000381469727,
                    o3: 125.9000015258789,
                    so2: 4.199999809265137,
                    pm2_5: 12.0,
                    pm10: 14.0,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::TWO
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 12:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 12:00', 'UTC'),
                temp_c: 29.2,
                temp_f: 84.6,
                is_day: 1,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                    code: 1003
                ),
                wind_mph: 7.6,
                wind_kph: 12.2,
                wind_degree: 170,
                wind_dir: 'S',
                pressure_mb: 1013.0,
                pressure_in: 29.92,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 56,
                cloud: 46,
                feelslike_c: 31.1,
                feelslike_f: 88.0,
                windchill_c: 29.2,
                windchill_f: 84.6,
                heatindex_c: 31.1,
                heatindex_f: 88.0,
                dewpoint_c: 19.6,
                dewpoint_f: 67.3,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 8.9,
                gust_kph: 14.4,
                uv: 7.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 297.1000061035156,
                    no2: 5.400000095367432,
                    o3: 134.5,
                    so2: 3.200000047683716,
                    pm2_5: 11.0,
                    pm10: 12.699999809265137,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::ONE
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 13:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 13:00', 'UTC'),
                temp_c: 30.2,
                temp_f: 86.4,
                is_day: 1,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                    code: 1003
                ),
                wind_mph: 8.5,
                wind_kph: 13.7,
                wind_degree: 149,
                wind_dir: 'SSE',
                pressure_mb: 1013.0,
                pressure_in: 29.9,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 51,
                cloud: 34,
                feelslike_c: 32.0,
                feelslike_f: 89.6,
                windchill_c: 30.2,
                windchill_f: 86.4,
                heatindex_c: 32.0,
                heatindex_f: 89.6,
                dewpoint_c: 19.0,
                dewpoint_f: 66.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 9.8,
                gust_kph: 15.8,
                uv: 8.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 283.70001220703125,
                    no2: 3.799999952316284,
                    o3: 133.0,
                    so2: 3.0,
                    pm2_5: 10.0,
                    pm10: 11.5,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::ONE
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 14:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 14:00', 'UTC'),
                temp_c: 30.7,
                temp_f: 87.3,
                is_day: 1,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                    code: 1003
                ),
                wind_mph: 10.3,
                wind_kph: 16.6,
                wind_degree: 133,
                wind_dir: 'SE',
                pressure_mb: 1012.0,
                pressure_in: 29.88,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 48,
                cloud: 52,
                feelslike_c: 32.2,
                feelslike_f: 90.0,
                windchill_c: 30.7,
                windchill_f: 87.3,
                heatindex_c: 32.2,
                heatindex_f: 90.0,
                dewpoint_c: 18.4,
                dewpoint_f: 65.1,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 11.9,
                gust_kph: 19.1,
                uv: 8.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 273.70001220703125,
                    no2: 2.799999952316284,
                    o3: 127.30000305175781,
                    so2: 2.700000047683716,
                    pm2_5: 8.899999618530273,
                    pm10: 10.100000381469727,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::ONE
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 15:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 15:00', 'UTC'),
                temp_c: 31.0,
                temp_f: 87.8,
                is_day: 1,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                    code: 1003
                ),
                wind_mph: 12.1,
                wind_kph: 19.4,
                wind_degree: 123,
                wind_dir: 'ESE',
                pressure_mb: 1011.0,
                pressure_in: 29.85,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 47,
                cloud: 46,
                feelslike_c: 32.5,
                feelslike_f: 90.5,
                windchill_c: 31.0,
                windchill_f: 87.8,
                heatindex_c: 32.5,
                heatindex_f: 90.5,
                dewpoint_c: 18.2,
                dewpoint_f: 64.8,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 13.9,
                gust_kph: 22.3,
                uv: 8.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 270.3999938964844,
                    no2: 2.4000000953674316,
                    o3: 123.0,
                    so2: 2.200000047683716,
                    pm2_5: 7.400000095367432,
                    pm10: 8.399999618530273,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::ONE
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 16:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 16:00', 'UTC'),
                temp_c: 29.7,
                temp_f: 85.5,
                is_day: 1,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                    code: 1003
                ),
                wind_mph: 12.5,
                wind_kph: 20.2,
                wind_degree: 121,
                wind_dir: 'ESE',
                pressure_mb: 1011.0,
                pressure_in: 29.85,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 52,
                cloud: 33,
                feelslike_c: 31.3,
                feelslike_f: 88.3,
                windchill_c: 29.7,
                windchill_f: 85.5,
                heatindex_c: 31.3,
                heatindex_f: 88.3,
                dewpoint_c: 18.7,
                dewpoint_f: 65.7,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 14.8,
                gust_kph: 23.8,
                uv: 7.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 270.3999938964844,
                    no2: 2.700000047683716,
                    o3: 121.5999984741211,
                    so2: 2.200000047683716,
                    pm2_5: 6.800000190734863,
                    pm10: 7.599999904632568,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::ONE
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 17:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 17:00', 'UTC'),
                temp_c: 28.9,
                temp_f: 84.0,
                is_day: 1,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                    code: 1003
                ),
                wind_mph: 11.4,
                wind_kph: 18.4,
                wind_degree: 134,
                wind_dir: 'SE',
                pressure_mb: 1011.0,
                pressure_in: 29.85,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 53,
                cloud: 46,
                feelslike_c: 30.2,
                feelslike_f: 86.4,
                windchill_c: 28.9,
                windchill_f: 84.0,
                heatindex_c: 30.2,
                heatindex_f: 86.4,
                dewpoint_c: 18.4,
                dewpoint_f: 65.1,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 15.4,
                gust_kph: 24.8,
                uv: 7.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 273.70001220703125,
                    no2: 3.5999999046325684,
                    o3: 117.30000305175781,
                    so2: 2.200000047683716,
                    pm2_5: 6.699999809265137,
                    pm10: 7.5,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::ONE
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 18:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 18:00', 'UTC'),
                temp_c: 28.5,
                temp_f: 83.3,
                is_day: 1,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                    code: 1003
                ),
                wind_mph: 10.3,
                wind_kph: 16.6,
                wind_degree: 142,
                wind_dir: 'SE',
                pressure_mb: 1011.0,
                pressure_in: 29.85,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 55,
                cloud: 27,
                feelslike_c: 29.9,
                feelslike_f: 85.8,
                windchill_c: 28.5,
                windchill_f: 83.3,
                heatindex_c: 29.9,
                heatindex_f: 85.8,
                dewpoint_c: 18.6,
                dewpoint_f: 65.5,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 14.5,
                gust_kph: 23.4,
                uv: 7.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 280.3999938964844,
                    no2: 5.199999809265137,
                    o3: 114.4000015258789,
                    so2: 2.299999952316284,
                    pm2_5: 6.699999809265137,
                    pm10: 7.599999904632568,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::ONE
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 19:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 19:00', 'UTC'),
                temp_c: 27.2,
                temp_f: 81.0,
                is_day: 1,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                    code: 1003
                ),
                wind_mph: 9.4,
                wind_kph: 15.1,
                wind_degree: 139,
                wind_dir: 'SE',
                pressure_mb: 1011.0,
                pressure_in: 29.85,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 60,
                cloud: 26,
                feelslike_c: 28.6,
                feelslike_f: 83.5,
                windchill_c: 27.2,
                windchill_f: 81.0,
                heatindex_c: 28.6,
                heatindex_f: 83.5,
                dewpoint_c: 18.7,
                dewpoint_f: 65.7,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 15.0,
                gust_kph: 24.1,
                uv: 7.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 283.70001220703125,
                    no2: 6.599999904632568,
                    o3: 110.19999694824219,
                    so2: 2.4000000953674316,
                    pm2_5: 6.800000190734863,
                    pm10: 7.599999904632568,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::ONE
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 20:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 20:00', 'UTC'),
                temp_c: 26.0,
                temp_f: 78.8,
                is_day: 1,
                condition: new Condition(
                    text: 'Sunny',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                    code: 1000
                ),
                wind_mph: 8.1,
                wind_kph: 13.0,
                wind_degree: 131,
                wind_dir: 'SE',
                pressure_mb: 1011.0,
                pressure_in: 29.86,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 63,
                cloud: 24,
                feelslike_c: 27.4,
                feelslike_f: 81.3,
                windchill_c: 26.0,
                windchill_f: 78.8,
                heatindex_c: 27.4,
                heatindex_f: 81.3,
                dewpoint_c: 18.4,
                dewpoint_f: 65.1,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 14.5,
                gust_kph: 23.4,
                uv: 7.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 297.1000061035156,
                    no2: 9.800000190734863,
                    o3: 98.69999694824219,
                    so2: 2.5,
                    pm2_5: 7.199999809265137,
                    pm10: 8.0,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::ONE
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 21:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 21:00', 'UTC'),
                temp_c: 25.7,
                temp_f: 78.3,
                is_day: 0,
                condition: new Condition(
                    text: 'Clear',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                    code: 1000
                ),
                wind_mph: 7.8,
                wind_kph: 12.6,
                wind_degree: 128,
                wind_dir: 'SE',
                pressure_mb: 1012.0,
                pressure_in: 29.88,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 63,
                cloud: 24,
                feelslike_c: 27.0,
                feelslike_f: 80.6,
                windchill_c: 25.7,
                windchill_f: 78.3,
                heatindex_c: 27.0,
                heatindex_f: 80.6,
                dewpoint_c: 18.1,
                dewpoint_f: 64.6,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 14.3,
                gust_kph: 23.0,
                uv: 1.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 327.1000061035156,
                    no2: 17.5,
                    o3: 78.0,
                    so2: 3.0,
                    pm2_5: 8.199999809265137,
                    pm10: 9.199999809265137,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::ONE
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 22:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 22:00', 'UTC'),
                temp_c: 25.2,
                temp_f: 77.4,
                is_day: 0,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                    code: 1003
                ),
                wind_mph: 7.6,
                wind_kph: 12.2,
                wind_degree: 132,
                wind_dir: 'SE',
                pressure_mb: 1012.0,
                pressure_in: 29.89,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 65,
                cloud: 40,
                feelslike_c: 26.6,
                feelslike_f: 79.9,
                windchill_c: 25.2,
                windchill_f: 77.4,
                heatindex_c: 26.6,
                heatindex_f: 79.9,
                dewpoint_c: 18.1,
                dewpoint_f: 64.6,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 14.5,
                gust_kph: 23.4,
                uv: 1.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 360.5,
                    no2: 23.700000762939453,
                    o3: 60.099998474121094,
                    so2: 3.299999952316284,
                    pm2_5: 9.199999809265137,
                    pm10: 10.600000381469727,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::ONE
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 23:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 23:00', 'UTC'),
                temp_c: 24.6,
                temp_f: 76.3,
                is_day: 0,
                condition: new Condition(
                    text: 'Clear',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                    code: 1000
                ),
                wind_mph: 7.4,
                wind_kph: 11.9,
                wind_degree: 127,
                wind_dir: 'SE',
                pressure_mb: 1013.0,
                pressure_in: 29.9,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 67,
                cloud: 20,
                feelslike_c: 26.1,
                feelslike_f: 79.0,
                windchill_c: 24.6,
                windchill_f: 76.3,
                heatindex_c: 26.1,
                heatindex_f: 79.0,
                dewpoint_c: 18.1,
                dewpoint_f: 64.6,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 15.0,
                gust_kph: 24.1,
                uv: 1.0,
                air_quality: ! $aqi ? null : new AirQuality(
                    co: 387.20001220703125,
                    no2: 27.399999618530273,
                    o3: 45.400001525878906,
                    so2: 3.0999999046325684,
                    pm2_5: 10.100000381469727,
                    pm10: 11.800000190734863,
                    us_epa_index: UsEpaIndex::GOOD,
                    gb_defra_index: UkDefraIndex::ONE
                ),
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            )
        ];
    }

    /**
     * Creates the hours for a future forecast day.
     */
    protected function newFutureHours(string $dt): array
    {
        return [
            new Hour(
                time_epoch: Carbon::parse($dt . ' 00:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 00:00', 'UTC'),
                temp_c: 23.4,
                temp_f: 74.1,
                is_day: false,
                condition: new Condition(
                    text: 'Patchy rain possible',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/176.png',
                    code: 1063
                ),
                wind_mph: 8.1,
                wind_kph: 13.0,
                wind_degree: 138,
                wind_dir: 'SE',
                pressure_mb: 1011.0,
                pressure_in: 29.86,
                precip_mm: 0.1,
                precip_in: 0.0,
                humidity: 77,
                cloud: 80,
                feelslike_c: 25.3,
                feelslike_f: 77.5,
                windchill_c: 23.4,
                windchill_f: 74.1,
                heatindex_c: 25.3,
                heatindex_f: 77.5,
                dewpoint_c: 19.1,
                dewpoint_f: 66.4,
                will_it_rain: 0,
                chance_of_rain: 61,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 16.6,
                gust_kph: 26.6,
                uv: null,
                air_quality: null,
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 03:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 03:00', 'UTC'),
                temp_c: 22.0,
                temp_f: 71.6,
                is_day: 0,
                condition: new Condition(
                    text: 'Clear',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                    code: 1000
                ),
                wind_mph: 6.0,
                wind_kph: 9.7,
                wind_degree: 148,
                wind_dir: 'SSE',
                pressure_mb: 1011.0,
                pressure_in: 29.86,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 83,
                cloud: 6,
                feelslike_c: 24.5,
                feelslike_f: 76.1,
                windchill_c: 22.0,
                windchill_f: 71.6,
                heatindex_c: 24.5,
                heatindex_f: 76.1,
                dewpoint_c: 19.1,
                dewpoint_f: 66.4,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 11.9,
                gust_kph: 19.1,
                uv: null,
                air_quality: null,
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 06:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 06:00', 'UTC'),
                temp_c: 21.0,
                temp_f: 69.8,
                is_day: 0,
                condition: new Condition(
                    text: 'Clear',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                    code: 1000
                ),
                wind_mph: 7.4,
                wind_kph: 11.9,
                wind_degree: 152,
                wind_dir: 'SSE',
                pressure_mb: 1012.0,
                pressure_in: 29.87,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 88,
                cloud: 5,
                feelslike_c: 21.0,
                feelslike_f: 69.8,
                windchill_c: 21.0,
                windchill_f: 69.8,
                heatindex_c: 21.0,
                heatindex_f: 69.8,
                dewpoint_c: 19.0,
                dewpoint_f: 66.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 13.4,
                gust_kph: 21.6,
                uv: null,
                air_quality: null,
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 09:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 09:00', 'UTC'),
                temp_c: 24.4,
                temp_f: 75.9,
                is_day: 1,
                condition: new Condition(
                    text: 'Sunny',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
                    code: 1000
                ),
                wind_mph: 8.1,
                wind_kph: 13.0,
                wind_degree: 165,
                wind_dir: 'SSE',
                pressure_mb: 1013.0,
                pressure_in: 29.92,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 74,
                cloud: 10,
                feelslike_c: 26.2,
                feelslike_f: 79.2,
                windchill_c: 24.4,
                windchill_f: 75.9,
                heatindex_c: 26.2,
                heatindex_f: 79.2,
                dewpoint_c: 19.6,
                dewpoint_f: 67.3,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 9.6,
                gust_kph: 15.5,
                uv: null,
                air_quality: null,
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 12:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 12:00', 'UTC'),
                temp_c: 29.2,
                temp_f: 84.6,
                is_day: 1,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                    code: 1003
                ),
                wind_mph: 7.6,
                wind_kph: 12.2,
                wind_degree: 170,
                wind_dir: 'S',
                pressure_mb: 1013.0,
                pressure_in: 29.92,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 56,
                cloud: 46,
                feelslike_c: 31.1,
                feelslike_f: 88.0,
                windchill_c: 29.2,
                windchill_f: 84.6,
                heatindex_c: 31.1,
                heatindex_f: 88.0,
                dewpoint_c: 19.6,
                dewpoint_f: 67.3,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 8.9,
                gust_kph: 14.4,
                uv: null,
                air_quality: null,
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 15:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 15:00', 'UTC'),
                temp_c: 31.0,
                temp_f: 87.8,
                is_day: 1,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                    code: 1003
                ),
                wind_mph: 12.1,
                wind_kph: 19.4,
                wind_degree: 123,
                wind_dir: 'ESE',
                pressure_mb: 1011.0,
                pressure_in: 29.85,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 47,
                cloud: 46,
                feelslike_c: 32.5,
                feelslike_f: 90.5,
                windchill_c: 31.0,
                windchill_f: 87.8,
                heatindex_c: 32.5,
                heatindex_f: 90.5,
                dewpoint_c: 18.2,
                dewpoint_f: 64.8,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 13.9,
                gust_kph: 22.3,
                uv: null,
                air_quality: null,
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 18:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 18:00', 'UTC'),
                temp_c: 28.5,
                temp_f: 83.3,
                is_day: 1,
                condition: new Condition(
                    text: 'Partly cloudy',
                    icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                    code: 1003
                ),
                wind_mph: 10.3,
                wind_kph: 16.6,
                wind_degree: 142,
                wind_dir: 'SE',
                pressure_mb: 1011.0,
                pressure_in: 29.85,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 55,
                cloud: 27,
                feelslike_c: 29.9,
                feelslike_f: 85.8,
                windchill_c: 28.5,
                windchill_f: 83.3,
                heatindex_c: 29.9,
                heatindex_f: 85.8,
                dewpoint_c: 18.6,
                dewpoint_f: 65.5,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 14.5,
                gust_kph: 23.4,
                uv: null,
                air_quality: null,
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            ),
            new Hour(
                time_epoch: Carbon::parse($dt . ' 21:00', 'America/Chicago')->timestamp,
                time: Carbon::parse($dt . ' 21:00', 'UTC'),
                temp_c: 25.7,
                temp_f: 78.3,
                is_day: 0,
                condition: new Condition(
                    text: 'Clear',
                    icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                    code: 1000
                ),
                wind_mph: 7.8,
                wind_kph: 12.6,
                wind_degree: 128,
                wind_dir: 'SE',
                pressure_mb: 1012.0,
                pressure_in: 29.88,
                precip_mm: 0.0,
                precip_in: 0.0,
                humidity: 63,
                cloud: 24,
                feelslike_c: 27.0,
                feelslike_f: 80.6,
                windchill_c: 25.7,
                windchill_f: 78.3,
                heatindex_c: 27.0,
                heatindex_f: 80.6,
                dewpoint_c: 18.1,
                dewpoint_f: 64.6,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.0,
                gust_mph: 14.3,
                gust_kph: 23.0,
                uv: null,
                air_quality: null,
                sig_ht_mt: null,
                swell_ht_mt: null,
                swell_ht_ft: null,
                swell_dir: null,
                swell_dir_16_point: null,
                swell_period_secs: null,
                water_temp_c: null,
                water_temp_f: null
            )
        ];
    }

    /**
     * Creates a new alert dto.
     */
    protected function newAlert(): Alert
    {
        return new Alert(
            headline: 'Air Quality Alert issued May 31 at 2:57PM CDT by NWS',
            msgtype: 'Alert',
            severity: 'Unknown',
            urgency: 'Unknown',
            areas: 'Collin; Dallas; Denton; Ellis; Henderson; Hood; Hunt; Johnson; Kaufman; Parker; Rockwall; Tarrant; Wise',
            category: 'Met',
            certainty: 'Unknown',
            event: 'Air Quality Alert',
            note: 'Alert for Collin; Dallas; Denton; Ellis; Henderson; Hood; Hunt; Johnson; Kaufman; Parker; Rockwall; Tarrant; Wise (Texas) Issued by the National Weather Service',
            effective: Carbon::parse('2023-06-01T04:09:00-05:00'),
            expires: Carbon::parse('2023-06-01T18:00:00-05:00'),
            description: (
                "...OZONE ACTION DAY...\n" .
                "The Texas Commission on Environmental Quality (TCEQ) has issued\n" .
                "an Ozone Action Day for the Dallas-Fort Worth area for Thursday,\n" .
                "June 1, 2023.\n" .
                "Atmospheric conditions are expected to be favorable for producing\n" .
                "high levels of ozone air pollution in the Dallas-Fort Worth area\n" .
                "on Thursday. You can help prevent ozone pollution by sharing a\n" .
                "ride, walking, riding a bicycle, taking your lunch to work,\n" .
                "avoiding drive-through lanes, conserving energy, and keeping your\n" .
                "vehicle properly tuned.\nFor more information on ozone:\n" .
                "Ozone: The Facts (www.tceq.texas.gov/goto/ozonefacts)\n" .
                "Air North Texas: (www.airnorthtexas.org)\n" .
                "EPA Air Now\n" .
                "(www.airnow.gov/index.cfm?action.local_state&STATEID=45&TAB=0)\n" .
                "Take care of Texas (www.takecareoftexas.org)\n" .
                "North Central Texas Council of Governments Air Quality\n" .
                "(www.nctcog.org/trans/air/index.asp)"
            ),
            instruction: ''
        );
    }
}
